// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmecM0vnZi6GaYYMlhlNwP7P41boqjKCI',
    appId: '1:453229654159:web:5c947c8e5de67506b440fa',
    messagingSenderId: '453229654159',
    projectId: 'jarvis-calendar-469216',
    authDomain: 'jarvis-calendar-469216.firebaseapp.com',
    storageBucket: 'jarvis-calendar-469216.firebasestorage.app',
    measurementId: 'G-0T7S1ST3S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNPh12ECXoXSagSWlX6EcwaoHh9f8jwFw',
    appId: '1:453229654159:android:0e2d1a86abd510a1b440fa',
    messagingSenderId: '453229654159',
    projectId: 'jarvis-calendar-469216',
    storageBucket: 'jarvis-calendar-469216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEaH4vMeC_tIWSLa5F4IKeOYrP556Nqag',
    appId: '1:453229654159:ios:d5f0009f2c9d101bb440fa',
    messagingSenderId: '453229654159',
    projectId: 'jarvis-calendar-469216',
    storageBucket: 'jarvis-calendar-469216.firebasestorage.app',
    iosClientId: '453229654159-o939f8r1rht95d73iejr8u18jhs15poc.apps.googleusercontent.com',
    iosBundleId: 'com.applitrack.applitrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEaH4vMeC_tIWSLa5F4IKeOYrP556Nqag',
    appId: '1:453229654159:ios:d5f0009f2c9d101bb440fa',
    messagingSenderId: '453229654159',
    projectId: 'jarvis-calendar-469216',
    storageBucket: 'jarvis-calendar-469216.firebasestorage.app',
    iosClientId: '453229654159-o939f8r1rht95d73iejr8u18jhs15poc.apps.googleusercontent.com',
    iosBundleId: 'com.applitrack.applitrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmecM0vnZi6GaYYMlhlNwP7P41boqjKCI',
    appId: '1:453229654159:web:e91c71866ae82759b440fa',
    messagingSenderId: '453229654159',
    projectId: 'jarvis-calendar-469216',
    authDomain: 'jarvis-calendar-469216.firebaseapp.com',
    storageBucket: 'jarvis-calendar-469216.firebasestorage.app',
    measurementId: 'G-RN0T7115RY',
  );
}
